### ISSUE TITLE
Tests that can not fail

### ISSUE THREAD

**Issue by RSynch** [tpm2-software/tpm2-tss#1023]
The integration tests esys-clear-control.int.c and esys-hierarchy-control.int.c both end the following way:
```
    goto_error_if_not_failed(r, "Error: ClockSet", error);

    return 0;

 error:
    return r;
```
An error is expected and makes the function return 0, but in case of an undesired success, the return value TPM2_RC_SUCCESS is returned, which is 0 as well.
To fix this, the end should be 
```
    return 1;
```

**Comment by tstruk** [comment]
Thanks for reporting, but both of the tests are valid. In the first case esys-clear-control.int.c
the Esys_ClearControl() disables execution of the TPM2_Clear() function so when TPM2_Clear() is called next it is expected to fail.
In the second case the Esys_HierarchyControl() disables the PLATFORM hierarchy so the subsequent call to Esys_ClockSet() is also expected to fail.
The goto_error_if_not_failed() macro is a bit misleading, because it has inverted logic, i.e. it returns error if the previous function didn't fail, which in both this cases is expected.
Hope that makes sense.

**Comment by AndreasFuchsSIT** [comment]
Thing is, that the macro evals to true if r == TSS2_TC_SUCCESS == 0 and does not change r. And under the error tag, r is returned. So if we fail we return 0 if we do not fail we jump to error and still return r = 0.
