### ISSUE TITLE
Test that can only work with the simulator

### ISSUE THREAD

**Issue by RSynch** [tpm2-software/tpm2-tss#1037]
The test _sapi-command-cancel_ uses the command _tcti_platform_command_, which sends special commands to the simulator. Thus this test can never be successful when using a HW TPM.

It probably should be skipped when running on anything other than the simulator.

**Comment by AndreasFuchsSIT** [comment]
Do you know what happens, if this is called for tcti-device ?
I guess it should be some TSS2_TCTI_RC_BAD_CONTEXT since the magic numbers should differ. In this case we can return 77 /* aka SKIP */.

I seem to remember that tcti-mssim and tcti-device shared the same magic number though, which would be a bug.

Thus my question.

**Comment by RSynch** [comment]
The two magic numbers are different, so BAD_CONTEXT is returned.
It can be done the way you proposed.

**Comment by AndreasFuchsSIT** [comment]
Awesome thanks for the patch !
