### ISSUE TITLE
Unable to get authorization to TPM2 after clearing ERROR 0x9a2

### ISSUE THREAD

**Issue by AshithPolepalli** [tpm2-software/tpm2-tss#1120]
I'm working on Nuc7i7BNH firmware TPM2.
Getting the following error on running command below, after performing following steps:

    TPM2 has been cleared by removing jumper and selecting option on boot.(as mentioned in NUC datasheet)

    $ tpm2_takeownership -o ownerpass -e endorsepass -l lockpass
    ERROR: Could not change hierarchy for Owner. TPM Error:0x9a2

couldn't understand what is the exact issue in setting password after clearing the TPM.

**Comment by AndreasFuchsSIT** [comment]
@AshithPolepalli Since this is either a TPM or a tpm2-tools bug I'll close it here.

Also: tpm2_takeownership has been deprecated and removed in favor of tpm2_changeauth (see https://github.com/tpm2-software/tpm2-tools/blob/fe03a879a45faeae87e90c58bae32ede59ff203e/CHANGELOG.md#L112)

Thus, I'd advice to switch to the latest versions and start from there...

Sorry to not be of bigger help...
