### ISSUE TITLE
libressl support?

### ISSUE THREAD

**Issue by alonbl** [tpm2-software/tpm2-tss#1235]
Hi,
I tried to build using libressl.
Missing functions: EVP_PKEY_CTX_set_rsa_oaep_md, EVP_PKEY_CTX_set0_rsa_oaep_label
I am unsure if these are mandatory or not for normal processing.
Can you please look into this?
Thanks!

**Comment by AndreasFuchsSIT** [comment]
Yes, they are mandatory.
See https://github.com/tpm2-software/tpm2-tss/pull/1207#issuecomment-440217659

Basically, the TPM uses OAEP with a label and SHA256, while libressl only supports empty label and SHA1. Thus, libressl would need to add support for this to be a possible crypto-backend for us.
This is because I don't want to reimplement all of OAEP in tpm2-tss.

If you are involved with libressl, I'd love to see support over there.

**Comment by alonbl** [comment]
Thanks!

I am not involved in libressl, I am Gentoo maintainer of crypto software,
we got request from users to use libressl, I will remove libressl option
from this package for now.

**Comment by AndreasFuchsSIT** [comment]
ok... I'll close this bug then for now...
