### ISSUE TITLE
Unresolved Symbol

### ISSUE THREAD

**Issue by aliraees1993** [tpm2-software/tpm2-tss#1272]
Hi. I am trying to compile on windows 10, openssl-64bit. But i am getting this error. I tried on multiple versions of openssl but no luck.

![image](https://user-images.githubusercontent.com/16216329/52951756-f0c94c80-3382-11e9-8095-2973dcadb868.png)

Kindly help.

**Comment by AndreasFuchsSIT** [comment]
Good question, next question...
I can only guess the following from similar sounding Linux problems:
If the compiler complains, you usually don't have the right path for header files.
If the linker complains, you have only set the headers path but not the libraries path.
This seems to be the latter case, so try to investigate if the libraries used for linking are indeed correct.

Besides this, I'd recommend comparing your build environment to the AppVeyor settings, since we do a compilation of tss for every single PR and HEAD.

**Comment by davidjmaria** [comment]
Win64 OpenSSL v1.0.2 works without any issues for me. 

If you're building it yourself make sure to put all of the files in the correct directories. 
- The lib files should be in C:\OpenSSL-Win64\lib
- The include directory should be at C:\OpenSSL-Win64\include\openssl
- The dlls/exe should be in C:\OpenSSL-Win64\bin
