### ISSUE TITLE
Do not depend on tpm_server if with-ptpm is specified

### ISSUE THREAD

**Issue by PeterHuewe** [tpm2-software/tpm2-tss#1278]
If --with-ptpm is specified there is no need to have the tpm_server installed.
Currently configure fails if --enable-integration --with-ptpm=/dev/tpm0 is specified, but no tpm_server is in path

**Comment by aberdery** [comment]
Hi,
A comment on this opened issue to indicate that another case where tpm_server is not needed but where configure currently fails is the usage of "--host=HOST" : e.g as soon as you want to build binaries to run on another platform than the one used for cross-compilation.

**Comment by AndreasFuchsSIT** [comment]
Hmmm... What's the idea of make check in cross-compilation in general though ?

**Comment by aberdery** [comment]
Maybe my misunderstanding here ?
I'm trying to "integrate" tpm2-tss on an embedded ARM platform. 
So, even if README indicates "this test suite should only be run against a TPM simulator", I was trying to build it including existing integration tests, as a starting point.

**Comment by williamcroberts** [comment]
You'd have to run the tests against the target device, and make check
runs it on the host device. So you wouldn't get what you want.

**Comment by aberdery** [comment]
Never said I would run make check.

Just said I thought I could benefit from both tss "core" libraries AND
existing tss "test" libraries as a starting point for the validation of the
integration of tpm2-tss on my platform.

First stage: being able to build all of that, hence my original comment
here.

**Comment by AndreasFuchsSIT** [comment]
So the idea of the `check_PROGRAMS` is that they are executed using `make check` or `make distcheck`. These commands are assume to be run on TARGET, not on HOST. Given that assumption, it makes sense to require `tpm_server` if `--enable-integration` without `--with-ptpm` is given.

In scenarios of cross-compilation, IMHO you should not enable unit or integration testing though the autotools harness, except if you have a HOST-simulation on TARGET (using qemu or wine or whatever) or the ability to remotely connect to a HOST device from TARGET.
In order to enable this, we would need to rework the TESTS harness inside the Makefile-test.am and the LOG_COMPILERs accordingly.

Until then, I'd say we stick with the current layout, except for the --with-ptpm option.

My recommendation for your scenario would be to just build and make check on HOST or to cross-compile without --enable-integration.
Or if you want to add support for cross-compilation testing using simulation wrappers, I'd be happy to merge them. Especially a wine-wrapper for mingw-cross-compilation would be very useful.

**Comment by aberdery** [comment]
Fine for me.
Thanks a lot for your clarifications.

**Comment by tstruk** [comment]
This has been fixed with commit https://github.com/tpm2-software/tpm2-tss/commit/21cca2acb7e88b212e64098288c8eaa018a7c3fe

Note that the enable flag has been renamed from --with-ptpm to --with-device
so the configure command should be:
```
$ ./configure --enable-integration --with-device=/dev/tpm0
```
