### ISSUE TITLE
2 tests out of the mandatory + optional ptpm tests fail

### ISSUE THREAD

**Issue by reanimus** [tpm2-software/tpm2-tss#1301]
Log is attached. My machine is a Dell XPS 9560, running BIOS version 0.1.12.1. I'm also seeing some errors when using tpm2-pkcs11, but I'm not sure if that's related (see [issue](https://github.com/tpm2-software/tpm2-pkcs11/issues/143) here)

[test-suite.log](https://github.com/tpm2-software/tpm2-tss/files/2929412/test-suite.log)

**Comment by AndreasFuchsSIT** [comment]
That error is related to the following:
- The test tries to make a key persistent inside the TPM using a certain handle.
- Your TPM already has a persistent object using this handle.
- This handle is 0x81000000
- I'll assume that you used your TPM with some software that made this a persistent key.

Quick solution:
Have a look at the tpm2_evictcontrol and remove the handle (caution, this may break the other software).

TODO for this bug:
- Have a more graceful error (i.e. skipped or error instead of fail)
- Use a different handle (the first one inside this handle range is very probable to be used elsewhere)

**Comment by reanimus** [comment]
Correct, re-running the tests after clearing the TPM yielded no errors.

**Comment by tstruk** [comment]
More graceful error code in this case could make the test case silently pass in case of a legit issue. If the issue is that a handle already exists the easiest way to fix that is to flush the object with that handle.
