### ISSUE TITLE
codecov rejecting PRs

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tss#1459]
#1454 is a good example of things we *do not* want codecov to do. I don't know what setting we're looking for but having codecov reject PRs due to ~0.02% reduction in code coverage is silly.

**Comment by flihp** [comment]
this looks like the docs for the feature: https://docs.codecov.io/docs/commit-status#section-patch-status

**Comment by AndreasFuchsSIT** [comment]
Well, we do have it
https://github.com/tpm2-software/tpm2-tss/blob/7da2391547c08157ce3046f8049aa527cfb105fc/.codecov.yml#L8

I assume it failed, because coverage was -1.22% for the file. I also did not know that it was measured per file.

What would a good threshold for "per file" be ?

**Comment by tstruk** [comment]
I'm not sure if there is a good solution to this problem. Ideally no PR should decrease the coverage, but in practice that won't be the case. We still want the codecov to mark the PRs that decrease the coverage by more than the 1% threshold, but since the merging is a manual process anyway we can make decision what's good and what can be merged.
