### ISSUE TITLE
dist-check fails but travis does not

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tss#1464]
1. Distcheck currently fails due to missing `tctildr.h` in dist-blob (@flihp)
2. Distcheck fails, but travis reports ok: https://travis-ci.org/tpm2-software/tpm2-tss/jobs/557930304
Maybe because of scan-build not failing (@AndreasFuchsSIT )

**Comment by AndreasFuchsSIT** [comment]
ok.....
> scan-build returns the value returned by build_command unless --status-bugs or --keep-going is used.
So we have to split things up and have scan-build go separate to the others...

**Comment by flihp** [comment]
It used to be the case that we ran the `distcheck` target for both clang and GCC. A failure in distcheck may not be be caught by clang for the reasons  you state (scan-build passes, obscures exit status of build) but the failure would be caught by the GCC build (doesn't obscure the exit status from `make`). There have been many changes to `.travis.yml` since and we no longer run `distcheck` for both compilers (56056303ffd56256b8d3fde747578a9de3a54bcf is the commit that stands out to me currently but I've only searched briefly).

**Comment by diabonas** [comment]
Yep, 56056303ffd56256b8d3fde747578a9de3a54bcf/#1399 is to blame. Tests on my local system worked fine because I used Clang 8 where this [behaviour has changed](https://reviews.llvm.org/D52530). The newer version isn't available in the Ubuntu 16.04 VM though, so calling `scan-build` separately seems to be the only thing we can do...

**Comment by flihp** [comment]
resolved in #1467
