### ISSUE TITLE
tcti-ldr spurious error messages

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tss#1482]
Since the switch in the tools I keep getting this error:
```
$ tpm2_pcrlist
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:116:handle_from_name() Failed to load TCTI for name "libtss2-tcti-default.so": libtss2-tcti-libtss2-tcti-default.so.so: cannot open shared object file: No such file or directory 
sha1: <snip>
```
Should we be printing the error for the default tcti, considering we have the fallback logic? Shouldn't we only print the error if it's not file not found?

**Comment by diabonas** [comment]
See #1480 for a pull request to downgrade this message from an error to a warning. As stated there, I would be happy to downgrade it even further to a debug message (especially considering the quite confusing `libtss2-tcti-libtss2-tcti-default.so.so` in the error text), while the currently suggested PR only restores the state from before the tss2-tctildr refactoring (where calling `Esys_Initialize` with a `NULL` TCTI also resulted in similar warnings).

**Comment by AndreasFuchsSIT** [comment]
The rational was to stick with WARNING, because we actually want distros to set the symlink libtss2-tcti-default.so to their default using e.g. update-alternatives or whatever they have...

**Comment by williamcroberts** [comment]
boo: not everything is a mainline distro and if make install is generating a warning you're wrong.

**Comment by AndreasFuchsSIT** [comment]
maybe make install needs to set a symlink to tcti-device then and tpm2-abrmd overwrites it on make install ?

**Comment by AndreasFuchsSIT** [comment]
So reopening to get ln-s into install-local

**Comment by diabonas** [comment]
Note that currently linking `libtss2-tcti-device.so` to `libtss2-tcti-default.so` doesn't do the same as the [default TCTI lookup routine](https://github.com/tpm2-software/tpm2-tss/blob/727fc47ea15941c29bac993c39fb1d2e5987f9ac/src/tss2-tcti/tctildr-dl.c#L163): the latter will [try `/dev/tpmrm0` and fall back to `/dev/tpm0`](https://github.com/tpm2-software/tpm2-tss/blob/727fc47ea15941c29bac993c39fb1d2e5987f9ac/src/tss2-tcti/tctildr-dl.c#L41-L50) if not available, while the former will [always use `/dev/tpm0` directly](https://github.com/tpm2-software/tpm2-tss/blob/727fc47ea15941c29bac993c39fb1d2e5987f9ac/src/tss2-tcti/tcti-device.c#L408).

Hence I don't know how to use `libtss2-tcti-default.so` properly: I want to use the in-kernel resource manager, so I have to set [`--with-tctidefaultconfig=/dev/tpmrm0`](https://github.com/tpm2-software/tpm2-tss/blob/d650eda45813424823f57ea0df43544c9995f57e/configure.ac#L118) during compile time to override the default [`NULL` configuration](https://github.com/tpm2-software/tpm2-tss/blob/727fc47ea15941c29bac993c39fb1d2e5987f9ac/src/tss2-tcti/tctildr-dl.c#L226) that would result in `/dev/tpm0` being loaded instead. This works for my use case, but for a distribution this means that you can't really switch between e.g. `libtss2-tcti-device.so` and `libtss2-tcti-tabrmd.so` using symlinks because `/dev/tpmrm0` will be an invalid configuration option for tpm2-abrmd.

I suppose that you could solve that particular problem by moving the tpmrm0/tpm0 auto discovery logic to [`tcti-device.c`](https://github.com/tpm2-software/tpm2-tss/blob/master/src/tss2-tcti/tcti-device.c), but the problem remains that you can only set the TCTI with `libtss2-tcti-default.so`, but not its configuration.

**Comment by AndreasFuchsSIT** [comment]
That's bad...
I think by default we would want to talk to /dev/tpmrm0 before /dev/tpm0.

IMHO we should fix this in tcti-device.c ?
What do y'all think ?

**Comment by williamcroberts** [comment]
I agree, the NULL config should always try the rm0 node first

**Comment by tstruk** [comment]
Fixed with https://github.com/tpm2-software/tpm2-tss/pull/1480
