### ISSUE TITLE
ESAPI should expose the API to retrieve cpHash

### ISSUE THREAD

**Issue by idesai** [tpm2-software/tpm2-tss#1533]
The function [tpm_calc_phash](https://github.com/tpm2-software/tpm2-tss/blob/7da2391547c08157ce3046f8049aa527cfb105fc/test/integration/sapi-session-util.c#L340) or [iesys_compute_cp_hashtab](https://github.com/tpm2-software/tpm2-tss/blob/70e9fae7ef535e7cf27a72ddbc818dfefcbdbdbb/src/tss2-esys/esys_iutil.c#L211) should be exposed through the ESAPI api interface.
This is required TPM commands that need cpHash like PolicySigned/ PolicySecret/ etc.

**Comment by tstruk** [comment]
What about Tss2_Sys_GetCpBuffer()?

**Comment by idesai** [comment]
> What about Tss2_Sys_GetCpBuffer()?
How do I access this function from ESAPI?

**Comment by idesai** [comment]
> What about Tss2_Sys_GetCpBuffer()?
> How do I access this function from ESAPI?

Something similar has been done to retrieve session nonceTPM [here](https://github.com/tpm2-software/tpm2-tss/commit/2a67f9e4b80d4875e4e70c9a6c899a749c57c608).

**Comment by AndreasFuchsSIT** [comment]
Yes, so I guess a TPM-less SYS_CONTEXT would allow for a seuence of Tss2_Sys_<command>_Prepare(); Tss2_Sys_GetCpBuffer().

If we want to make it systematic, I guess I'd like to introduce a library next to tss2-esys.so that exposes the cpHash functions. Tss2_util_<command>_cpHash(hashAlg, obj1, obj2, param1, param2) or similar I guess ?
