### ISSUE TITLE
Please clarify use of --enable-tcti-device-async

### ISSUE THREAD

**Issue by jhealyt** [tpm2-software/tpm2-tss#1551]
If I configure with the flag --enable-tcti-device-async, then should I desist from specifying these two further flags also?

--with-tctidefaultconfig=/dev/tpmrm0
--with-tctidefaultmodule=libtss2-tcti-device.so

Unrelatedy... what does "--enable-tcti-partial-reads" actually do?

**Comment by AndreasFuchsSIT** [comment]
device-async and partial-reads enable use of the new features of the linux kernel since version 5.something for asynchronous and partial reading of /dev/tpm* This allows users to make use of the Esys_*_Async/_Finish functions for a mainloop-driven design.

tctidefault is used if you don't want to use the current automatic discovery mechanism of "tpm2-abrmd via dbus, tpmrm0, tpm0, mssim" but only ask for one specific one.

**Comment by jhealyt** [comment]
So when you specify --enable-tcti-device-async, which device does it use in "/dev"?

Does it use "/dev/tpm0" with some trickery to allow concurrency?

Or does it use "/dev/tpmrm0" which is innately capable of concurrency?

**Comment by AndreasFuchsSIT** [comment]
device-async has no influence on which /dev node is opened. It only uses O_NONBLOCK for the open instead of blocking mode. That's already it...

tctildr is responsible for actually loading tctis and it will try to auto-discover a symbolic linked "tcti-default" and then "dbus, tpmrm0, tpm0, mssim":
https://github.com/tpm2-software/tpm2-tss/blob/30afabfc81496bc8a225e67b4d090ba1e169a22a/src/tss2-tcti/tctildr-dl.c#L32-L55
