### ISSUE TITLE
Should we get rid of libgcrypt

### ISSUE THREAD

**Issue by tstruk** [tpm2-software/tpm2-tss#1676]
Libgcrypt was the first crypto backend for ESAPI that was added in v2.0. After that we introduced openssl in v2.1, and both are supported currently. In v3.0 with the introduction with FAPI the only usable crypto backend is openssl unless FAPI is disabled at config time. 
Since by default FAPI is enabled we have an unusable gcrypt code that needs to maintained.
Maybe we should just get rid of libgcrypt in 3.1?

**Comment by AndreasFuchsSIT** [comment]
Hmmmm... since CI works, why not keep it ?
In the end, we even added mbed-tls / -crypto as backend for esys.
So I'd vote to keep it for now.
Maybe we warn about it being deprecated and thus allow us to remove it in any minor revision ?

**Comment by AndreasFuchsSIT** [comment]
I guess, 3.0.0 would be a good time to drop this if we ever want to.

@tstruk @williamcroberts Thoughts ?

**Comment by williamcroberts** [comment]
> I guess, 3.0.0 would be a good time to drop this if we ever want to.
> 
> @tstruk @williamcroberts Thoughts ?

I'm 100% Ok will killing libgcrypt. I would float a mailer on the list and see if any users object.

**Comment by emmanuel-deloget** [comment]
As a user, I see no issue with this. On the contrary, as it would simplify my dependency-related headaches :)

**Comment by diabonas** [comment]
I went through the distributions listed on [Repology](https://repology.org/project/tpm2-tss/versions) to see which backend they are using. The only distribution I could find that exclusively uses gcrypt is [Ataraxia Linux](https://github.com/ataraxialinux/ataraxia/commit/de886f93759429f6fcb124bd5e5b719567e8e37c#diff-1bc63a20d6b798cd980983ed1ca1787a) (pinging @ataraxialinux, @protonesso), and that has been a very recent change less than a week ago, apparently in an effort to get rid of a custom patch to build with LibreSSL instead of OpenSSL. All other distributions either offer a compile-time choice between the two backends like [Gentoo](https://gitweb.gentoo.org/repo/gentoo.git/tree/app-crypt/tpm2-tss/tpm2-tss-2.4.1.ebuild?id=ec6e9c276a25be30d330d524f7238eade26d24f3#n63), or (by far the majority) use the default OpenSSL backend.

Personally, as well as speaking as a packager for Arch Linux, I see no issue with removing support for gcrypt.

**Comment by AndreasFuchsSIT** [comment]
Since this is one of two remaining issues for 3.0, we should start making a decision.

I am in favor if removing.
@tstruk What do you think ?

**Comment by tstruk** [comment]
As far as I know debian also uses libgcrypt:
https://packages.debian.org/buster/libtss2-esys0
Might talk to the maintainer first before we remove it.
I will shut them an email.

**Comment by tstruk** [comment]
No problem for debian to move to OpenSSL. PR on it's way.

**Comment by protonesso** [comment]
Please fix build and linking on libressl

вс, 28 июн. 2020 г., 15:02 Jonas Witschel <notifications@github.com>:

**Comment by AndreasFuchsSIT** [comment]
> Please fix build and linking on libressl

Last time I checked, libressl did not support OAEP labels for encrypt.
So libressl needs to support this in order to be an allowed backend.
