### ISSUE TITLE
Coverity: Improper use of negative value (NEGATIVE_RETURNS)

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tss#1899]
Coverity is complaining about `Passing ctx->fd to close, which cannot accept a negative number.`
https://github.com/tpm2-software/tpm2-tss/blob/482ed2ed42edb2e9a818f7b6a1c15fbee2d7c4a3/src/tss2-tcti/tcti-pcap-builder.c#L315
called via
https://github.com/tpm2-software/tpm2-tss/blob/482ed2ed42edb2e9a818f7b6a1c15fbee2d7c4a3/src/tss2-tcti/tcti-pcap-builder.c#L255

@joholl Would you mind ?

**Comment by joholl** [comment]
I'm on it

**Comment by joholl** [comment]
This seems to be a false positive, not a bug. The file descriptor cannot be negative since proper error handling is implemented.

https://github.com/tpm2-software/tpm2-tss/blob/198201e726eb8bea3fa3c17efd2bda992355f6b3/src/tss2-tcti/tcti-pcap-builder.c#L220-L224

Also, according to `man 2 close`, `close` does indeed take a signed integer.

> SYNOPSIS
>       #include <unistd.h>
>
>       int close(int fd);

Unfortunately, I have a hard time getting Coverity to scan my branch to verify if [my patch](joholl/tpm2-tss@e0ccdbbb) solves the "defect". Could you kindly verify this? If you want, I can submit a PR to your repo @AndreasFuchsSIT . If my patch does not fix it, casting the `close` param might do the trick.

**Comment by AndreasFuchsSIT** [comment]
I have to agree, close should also consume negative values... Weird coverity bug...
I'll triage the scan item accordingly...
