### ISSUE TITLE
Does Esys_EvictControl return an incorrect value?

### ISSUE THREAD

**Issue by Superhepper** [tpm2-software/tpm2-tss#1930]
When evicting a persistent object using Esys_EvictControl it seems as the returned value is ESYS_TR_NONE.

Though the specification states that:
**TSS Enhanced System API (ESAPI) Specification Version 1.00 Revision 08**
> The metadata including the authValue and persistentHandle is removed from the esysContext.
> If the ESYS_TR object on input was a persistent object, this parameter will not return a ESYS_TR object but instead will return 
> ESYS_TR_NULL. Also the metadata in the ESYS_CONTEXT regarding the ESYS_TR object will be removed and the ESYS_TR object 
> will be marked as invalid.

When I look at the code I can see that the value returned is initialized to ESYS_TR_NONE.
https://github.com/tpm2-software/tpm2-tss/blob/31c961993d42afb4a692ede4c13d9cdf9abb240d/src/tss2-esys/api/Esys_EvictControl.c#L296

And here it is once again set to ESYS_TR_NONE even though the input was a persistent handle.
https://github.com/tpm2-software/tpm2-tss/blob/31c961993d42afb4a692ede4c13d9cdf9abb240d/src/tss2-esys/api/Esys_EvictControl.c#L362

So my question is am I missing something or is this a bug?

**Comment by AndreasFuchsSIT** [comment]
That's a bug in the spec.
It read ESYS_TR_NONE.
@williamcroberts FYI

Some background: ESYS_TR_NONE was originally called ESYS_TR_NULL, but we renamed it before the release of the spec, because of potential confusion with ESYS_TR_RH_NULL. So ESYS_TR_RH_NULL is the ephemeral-/NULL-Hierarchy; an actual TPM object. ESYS_TR_NONE means "no object"

**Comment by Superhepper** [comment]
Ah that makes sense. Thank you for the answer.
