### ISSUE TITLE
Build warning TCL_SUBS, PERL_PATH, MSCGEN_PATH 

### ISSUE THREAD

**Issue by kgold2** [tpm2-software/tpm2-tss#2067]
Ubuntu 20 groovy, TSS Branch '2.4.x' gives these warnings:

  DXGEN  Doxyfile
warning: Tag 'TCL_SUBST' at line 242 of file 'Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'PERL_PATH' at line 2220 of file 'Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'MSCGEN_PATH' at line 2242 of file 'Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"

... and if you're starting to think, "Maybe we should just build the man pages once and commit them rather than having the end user build them as part of the TSS build."  ...  :-)

**Comment by williamcroberts** [comment]
> Ubuntu 20 groovy, TSS Branch '2.4.x' gives these warnings:
> 
> DXGEN Doxyfile
> warning: Tag 'TCL_SUBST' at line 242 of file 'Doxyfile' has become obsolete.
> To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
> warning: Tag 'PERL_PATH' at line 2220 of file 'Doxyfile' has become obsolete.
> To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
> warning: Tag 'MSCGEN_PATH' at line 2242 of file 'Doxyfile' has become obsolete.
> To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
> 
> ... and if you're starting to think, "Maybe we should just build the man pages once and commit them rather than having the end user build them as part of the TSS build." ... :-)

@kgold2 we've been over these doxygen "errors", which are really warnings, with you in excruciating detail numerous times and how well doxygen can be noisy. We silenced it on master. I doubt will back port this feature. We've also detailed, that you can just not build the docs with `--disable-doxygen-doc` if you don't need em, just add that flag. If you need them, ignore the warnings, as long as you get docs built.

Committing auto-generated stuff is a bad idea, something will get out of sync if it's not automated by the CI or checked that it's done by the CI. The first approach is bad, because the CI would have commit access to code, the second would work but it'd be one more CI step.

I think a better approach to avoid this is to package the docs with the release tarball which is what we do with tpm2-tools man pages, which would reduce the burden on someone building plus reduce their build time. But for those building from git clone's you may still get this noise for Doxygen.

**Comment by williamcroberts** [comment]
I hooked the build so you can pre-make doxygen-doc in make dist, thus absolving a package builder of doing it (see diff below). But I don't see a whole bunch of benefit. If you just don't have doxygen installed, it won't even try to build them and its also by passable with --disable-doxygen-doc. The only case the existing model doesn't cover is when a package builder wants the manpages but doesn't want to satisfy the doxygen requirement, which hasn't happened.

```diff
diff --git a/Makefile.am b/Makefile.am
index 183289f743f8..1a613a60a7dd 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -654,8 +654,9 @@ man3_MANS = \
     man/man3/Tss2_TctiLdr_Finalize.3 \
     man/man3/Tss2_TctiLdr_FreeInfo.3 \
     man/man3/Tss2_TctiLdr_GetInfo.3 \
-    man/man3/Tss2_TctiLdr_Initialize.3 \
-    $(DOXYMAN3)
+    man/man3/Tss2_TctiLdr_Initialize.3
+
+dist_man3_MANS = $(DOXYMAN3)
 
 man7_MANS = \
     man/man7/tss2-tcti-device.7 \
@@ -742,7 +743,8 @@ EXTRA_DIST += \
 
 CLEANFILES += \
     $(man3_MANS) \
-    $(man7_MANS)
+    $(man7_MANS) \
+    $(dist_man3_MANS)
 
 # function to transform man .in files to man pages
 # $1: target
@@ -754,3 +756,11 @@ define make_man
     $(SED) 's/[@]VERSION[@]/$(PACKAGE_VERSION)/g' "$1_tmp" > $1 && \
     rm "$1_tmp"
 endef
+
+dist-hook:
+if !DOXYMAN
+# If doxygen-doc is not enabled, we want to complain that you need doxygen-doc for make dist,
+# so hook the target and complain.
+	@(>&2 echo "You must build with doxygen-doc enabled for make dist. This is a requirement for the distribution of manpages")
+	@exit 1
+endif
```
