### ISSUE TITLE
FAPI API usage

### ISSUE THREAD

**Issue by shekharpaty** [tpm2-software/tpm2-tss#2505]
Hello Experts,
When i use Fapi_CreateSeal and Fapi_Unseal serially in C program I see some issues with the sealing the data and later, i was not be able to seal the key again even with tss2_createseal , to reproduce the issue I tried from the command line 
`tss2_createseal --path=/HS/SRK/code6 --authValue="" --type="noDa" --data="test2"`
`ERROR:fapi:src/tss2-fapi/fapi_util.c:1071:ifapi_load_primary_finish() ErrorCode (0x00060020) The persistent handle 0x81000001 does not exist. The TPM state and the keystore state do not match. `
`ERROR:fapi:src/tss2-fapi/fapi_util.c:1403:ifapi_get_sessions_finish() Load primary. ErrorCode (0x00060020) `
`ERROR:fapi:src/tss2-fapi/fapi_util.c:3412:ifapi_key_create() ErrorCode (0x00060020)  FAPI create session `
`ERROR:fapi:src/tss2-fapi/api/Fapi_CreateSeal.c:268:Fapi_CreateSeal_Finish() Key create ErrorCode (0x00060020) `
`ERROR:fapi:src/tss2-fapi/api/Fapi_CreateSeal.c:123:Fapi_CreateSeal() ErrorCode (0x00060020) CreateSeal `
`Fapi_CreateSeal(0x60020) - fapi:The key was not found`

sample c program how I have invoked FAPI APIS
    ` r = Fapi_Initialize(&fapi_context, NULL);`
    ` r = Fapi_Provision(fapi_context, NULL, NULL, NULL);`
   `  r = Fapi_CreateSeal(fapi_context, "/HS/SRK/code6", "noDa,0x81000004", 1 ,"","","0x67");`
   `  r = Fapi_Unseal(fapi_context, "/HS/SRK/code6", &result, &tmp);`

**Comment by JuergenReppSIT** [comment]
* Your C code should work if FAPI was not provisioned before. But only one byte "0" will be sealed.
   Were there any error messages when the C code was executed?
* The error messages after executing tss2_createseal occur because the /SRK (with persistent handle 0x81000001) was deleted after the provisioning without using the FAPI interface. (e.g. tpm2_clear or tpm2_evictcontrol). The SRK is needed to encrypt the data sealed by Fapi_CreateSeal.
If the /SRK was removed with tpm2_evictcontrol you could try to recreate the SRK (e.g. ecc) :
   ` tpm2_createprimary -C o -g sha256 -G ecc -c srk.ctx`
   `tpm2_evictcontrol -C o -c srk.ctx 0x81000001`
After tpm2_clear the recreation is not possible.
