### ISSUE TITLE
Tss2_Sys_PolicyAuthorize in case trial session

### ISSUE THREAD

**Issue by khanhnt93** [tpm2-software/tpm2-tss#555]
I'm using TPM2_PolicyAuthorize to create policy digest. In document, in case I use trial session, TPM2_PolicyAuthorize just require keySign and policyRef to create policy digest. 
So in TSS library, why I must must pass checkTicket to PolicyAuthorize?
The code check null checkTicket in Tss2_Sys_PolicyAuthorize.c, line 45.

**Comment by tstruk** [comment]
Please see the NOTE2 in 23.16 TPM2_PolicyAuthorize of https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-3-Commands-01.38.pdf.
It states:
"The unmarshaling process requires that a proper TPMT_TK_VERIFIED be provided for checkTicket
but it may be a NULL Ticket. A NULL ticket is useful in a trial policy, where the caller uses the TPM
to perform policy calculations but does not have a valid authorization ticket."

This might be confusing, because a NULL ticket is not really a NULL pointer, but a ticket with the tag set to TPM2_ST_NULL.

**Comment by khanhnt93** [comment]
I solved my problems. Thank you very much.
