### ISSUE TITLE
Handle ax_code_coverage.m4

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tss#880]
I'm really unhappy with the current situation that code-coverage is not working under ubuntu 16.04 LTS unless you manually download the latest autoconf-archive manually.
I did not include the file originally because of I did not want to dive into the license rabbit hole.

Anyways. The file is provided under LGPL 2.1 or later. (http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_code_coverage.m4) So I was thinking that since it's only inside the m4 directory and not part of the main code base, we could provide it in this repo and the tar ball as well.

@tstruk @flihp what do you guys say ? Should / Can we include it ?

**Comment by williamcroberts** [comment]
You're still distributing it.

If you get this working, you can start running newer version of ubuntu, and other OSs like fedora
https://github.com/tpm2-software/tpm2-tss/pull/820

make check was hanging, and I never figured out why.

Another perk, is that you can test 100% locally.

**Comment by AndreasFuchsSIT** [comment]
@williamcroberts I know, I want to distribute it with the repo and tar-ball.

I think I don't know what you mean with the rest ?

**Comment by williamcroberts** [comment]
@AndreasFuchsSIT 
If you get the docker container working, you get an updated version of ubuntu, and one can set up containers for Fedora, etc, so you can test on those images. That docker image has ax code coverage installed and ready to go. I use this in the tools to build tss and abrmd.

The build process with containers is:
1. get the container image from dockerhub
2. Launch the build and test process in the container

In step 2, `make check` hung for me, and I don't know why. That's why I stopped working on it, lack of time to debug it.

Currently with travis, you can get the image, but there is nothing I found that says , "run the travis yaml file", ie replicating your build/test procedure on the server. With the docker image approach, the build/test logic is moved into a script, so you can literally execute everything locally exactly the way it would happen on the server.

**Comment by AndreasFuchsSIT** [comment]
@williamcroberts I see.

But that's not really my concern right now.

I've gotten feedback from people running Ubuntu 16.04 who checked out master and tried to build, but configure died. This happens as soon as you have lcov installed on your system.

The reason is that Ubuntu 16.04's version of autoconf-archive is incompatible with its version of lcov.

Even though the bug is with Ubuntu, I guess we need to work around it. One way would be to document the bug in README.md, the other way to add to master the more recent version of ax_code_coverage.m4.

I prefer the latter, thus my question if others see LGPL as a blocking point. In that case I'd go with the former...

**Comment by williamcroberts** [comment]
Oh really, it worked for me. I know it's broken with 14.04

**Comment by AndreasFuchsSIT** [comment]
Hmmm... did you have lcov installed when you ran ./configure ?

**Comment by martinezjavier** [comment]
@williamcroberts @AndreasFuchsSIT I think we are mixing too many discussions in this thread:

a) Distributing a LGPL licensed m4 macro in a BSD project.
b) Using a custom container image instead of Travis VM to have more flexibility on OS and version used.
c) A bug in some Ubuntu releases where the ax_code_coverage.m4 in its autoconf-archive package doesn't play well with their own lcov version.

For (a), my understanding is that's not possible since as @williamcroberts we will be distributing LGPL code in a BSD licensed project. Some m4 macros have license exception where the copyright owners give unlimited permission to copy and distribute the output of the autoconf m4 macro, for example [ax_check_compile_flag](https://www.gnu.org/software/autoconf-archive/ax_check_compile_flag.html).

In that case you can't distribute the macro but you can distribute the generated configure script. I think that makes sense if you only distribute the tarball but not in the case where you have a public git repository, but even this isn't possible with ax_code_coverage AFAICT. I'm not a lawyer though so I may be wrong, etc.

I agree with @williamcroberts about (b), it would be nice to be flexible and use current distributions releases in the CI pipeline since that will be more aligned to what users have.

For (c), I don't think upstream could do much to workaround problems in distributions. If there's a problem then I think that a bug should be filled for Ubuntu and work with them to get the issue fixed.
